### ISSUE TITLE
why not just rebase with a click?

### ISSUE THREAD

**Issue by andreineculau** [MatthieuLJ/StashRebaseWorkflow#2]
I haven't tried your plugin yet,
but why not also add a "Rebase" button that would just rebase (whenever possible) the PR on top of the parent branch?

**Comment by MatthieuLJ** [comment]
Mostly because it's not really what I needed at the time and also it's probably much more work. Would be great if you or somebody looked into it.
There are a few things to think about though... should the button be grayed out when it is not possible to rebase without conflicts? If so, then it will need to check whenever the pull request is updated or the branch to merge to is...
Beside that, I don't think it should be too complicated.

**Comment by andreineculau** [comment]
you can have rebase conflicts, without having merge conflicts, so if
anything:

a rebase button should be greyed out when there are merge conflicts,
otherwise, just try to rebase

On Fri, Nov 13, 2015 at 5:16 PM, MatthieuLJ notifications@github.com
wrote:

> Closed #2 https://github.com/MatthieuLJ/StashRebaseWorkflow/issues/2.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/MatthieuLJ/StashRebaseWorkflow/issues/2#event-463758205
> .

## 

andreineculau.com http://www.andreineculau.com
